[package]
name = "gnome-search-providers-jetbrains"
description = "Gnome search providers for recent projects from Jetbrains IDEs"
readme = "README.md"
homepage = "https://github.com/lunaryorn/gnome-search-providers-jetbrains"
repository = "https://github.com/lunaryorn/gnome-search-providers-jetbrains"
version = "1.7.2-alpha.0"
license = "MPL-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"
# We don't publish this to crates.io; you can't install it with cargo install
# because you'd miss the required service and configuration files, and you
# wouldn't want to depend on it either.
publish = false

[dependencies]
globwalk = "^0.8"
regex = "^1.4"
lazy_static = "^1.4"
dirs = "^4.0"
elementtree = "^0.5"
anyhow = "^1.0"
log = { version = "^0.4", features = ["release_max_level_info"] }
clap = { version = "^2.33", default-features = false }
gnome-search-provider-common = { path = "./crates/common" }

[dev-dependencies]
pretty_assertions = "^1"
rust-ini = "^0.17"

[workspace]
members = ["./crates/common"]

[package.metadata.release]
pre-release-commit-message = "Release {{version}}"
post-release-commit-message = "Bump version to {{next_version}}"
tag-prefix = ""
tag-message = "Version {{tag_name}}"
pre-release-replacements = [
    # Update the changelog
    { file="CHANGELOG.md", search="## \\[Unreleased\\]", replace = "## [Unreleased]\n\n## [{{version}}] – {{date}}", exactly = 1 },
    { file="CHANGELOG.md", search="HEAD", replace = "{{tag_name}}", exactly = 1 },
    { file="CHANGELOG.md", search="\\[Unreleased\\]: ", replace = "[Unreleased]: https://github.com/lunaryorn/gnome-search-providers-jetbrains/compare/{{tag_name}}...HEAD\n[{{version}}]: ", exactly = 1 },
]
disable-publish = true
