# Don't publish anything
publish = false
# Only release from main
allow-branch = ["main"]

# Use the same tag for all crates in this workspace.
# crates in crates/ use tag = false
tag-name = "v{{version}}"

# Release all at once, and share the version among all crates
shared-version = true

# I prefer these messages over the default (cargo-release) messages
tag-message = "Version {{tag_name}}"
pre-release-commit-message = "Release {{version}}"
