[package]
name = "gnome-search-provider-common"
description = "Common code for Gnome search providers"
version = "1.10.0"
homepage = "https://codeberg.org/flausch/gnome-search-providers-jetbrains"
repository = "https://codeberg.org/flausch/gnome-search-providers-jetbrains"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"
license = "MPL-2.0"
# We don't publish this to crates.io; because it's purely used for my search providers as git dependency.
publish = false

[dependencies]
indexmap = "^1.6"
zbus = "2.0.0"
tracing = "^0.1"
tracing-log = "^0.1"
tracing-journald = "0.2.2"
tracing-subscriber = { version = "0.3.5", features = [
    "registry",
    "parking_lot",
    "env-filter",
] }
tracing-futures = { version = "0.2.5", default-features = false, features = [
    "std-future",
    "futures-03",
] }
futures-util = "^0.3"
futures-channel = "^0.3"
gio = { version = "0.15.2", features = ["v2_60"] }
glib = { version = "0.15.2", features = ["log"] }
libc = "^0.2"
async-trait = "^0.1"

[dev-dependencies]
pretty_assertions = "^1"

[package.metadata.release]
shared-version = true
tag = false
